on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 'Testing Github action'
        run: pwd

      - name: 'before'
        run: ls

      - uses: actions/checkout@v3

      - name: 'after'
        run: ls